# DOOM alacritty
# configuration for alacritty, the GPU enhanced terminal emulator.
env:
  TERM: xterm-256color

window:
  dynamic_padding: true
  opacity: 0.7

  padding:
    x: 0
    y: 0

font:
  normal:
    family: Terminus
    style: Regular

  bold:
    family: Terminus
    style: Bold

  italic:
    family: Terminus
    style: Italic

  bold_italic:
    family: Terminus
    style: Bold Italic

  size: 11

  offset:
    x: 0
    y: 0

cursor:
  style: Underline

live_config_reload: true
colors:
  # COLORSCHEME: gruvbox_dark.yaml
  # Default colors
  primary:
    # low contrast: background: '0x282828'
    background: "0x1d2021"
    # soft contrast: background = '0x32302f'
    foreground: "0xebdbb2"

  # Normal colors
  normal:
    black: "0x1d2021"
    red: "0xcc241d"
    green: "0x98971a"
    yellow: "0xd79921"
    blue: "0x458588"
    magenta: "0xb16286"
    cyan: "0x689d6a"
    white: "0xa89984"

  # Bright colors
  bright:
    black: "0x928374"
    red: "0xfb4934"
    green: "0xb8bb26"
    yellow: "0xfabd2f"
    blue: "0x83a598"
    magenta: "0xd3869b"
    cyan: "0x8ec07c"
    white: "0xebdbb2"
  cursor:
    text: "0xd8d8d8"
    cursor: "0xd8d8d8"

  # Normal colors
  selection:
    text: "0x000000"
    background: "0xb3d7ff"
  dim:
    black: "0x31363b"
    red: "0x783228"
    green: "0x17a262"
    yellow: "0xb65619"
    blue: "0x1b668f"
    magenta: "0x614a73"
    cyan: "0x186c60"
    white: "0x63686d"
