# DOOM alacritty config file
# configuration for alacritty, the GPU enhanced terminal emulator.
env:
  TERM: xterm-256color

window:
  dynamic_padding: true
  opacity: 0.5

  padding:
    x: 5
    y: 5

font:
  normal:
    family: Scientifica
    style: Regular

  bold:
    family: Scientifica
    style: Bold

  italic:
    family: Scientifica
    style: Italic

  bold_italic:
    family: Scientifica
    style: Bold Italic

  size: 12

  offset:
    x: 0
    y: 0

cursor:
  style: Underline

live_config_reload: true
colors:
  primary:
    background: '#000000'
    foreground: '#edeff0'

  # Normal colors
  normal:
    black: '#0c0e0f'
    red: '#df5b61'
    green: '#78b892'
    yellow: '#de8f78'
    blue: '#6791c9'
    magenta: '#bc83e3'
    cyan: '#67afc1'
    white: '#e4e6e7'

  # Bright colors
  bright:
    black: '#464646'
    red: '#e8646a'
    green: '#81c19b'
    yellow: '#e79881'
    blue: '#709ad2'
    magenta: '#c58cec'
    cyan: '#70b8ca'
    white: '#f2f4f5'
  cursor:
    text: '#d8d8d8'
    cursor: '#d8d8d8'

  # Normal colors
  selection:
    text: '#000000'
    background: '#b3d7ff'
  dim:
    black: '#31363b'
    red: '#783228'
    green: '#17a262'
    yellow: '#b65619'
    blue: '#1b668f'
    magenta: '#614a73'
    cyan: '#186c60'
    white: '#63686d'
